### ISSUE TITLE
Web site rendering is mediocre on mobiles devices

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#52] opened 2012-12-12 15:18 UTC
Should work on tablets as well as full-screen devices (and the blog should look good on cellphones, at least).

**Comment by jiffyclub** [comment] 2012-12-12 16:22
That's pretty vague! The current state is useable, but not beautiful, on small screens. It's certainly an improvement over the WordPress site. Things I've noticed specifically need improvement for mobile devices:
- Titles are off center
  - This is caused by the `div.title h1 {margin: }` style in `swc.css`. I think we should just get rid of that, I don't see it doing anything.
- Next/Previous buttons end up jumbled with the title on pages that have those buttons.
  - I think this can be fixed using Bootstrap's row/span classes, but I haven't perfected it.

**Comment by gvwilson** [comment] 2012-12-12 16:30
This feels like it's going to be a lot of work, so let's defer to the 
new year...

**Comment by jiffyclub** [comment] 2012-12-12 16:38
I'll see what I can do on the two things above. They shouldn't be too bad and the blog navigation is basically unusable on a phone right now so we don't want to launch with that.

**Comment by jiffyclub** [comment] 2012-12-13 01:11
Okay, with the latest revision in SVN I think the title/nav behaviour is sensible on small devices.

**Comment by npch** [comment] 2013-01-28 10:11
I've raised a [new issue 256](https://github.com/swcarpentry/website/issues/256) with a specific rendering bug to do with menus on iPhones.

**Comment by wking** [comment] 2013-02-26 12:18
This seems to be complete.  Shall we close it?

**Comment by npch** [comment] 2013-02-26 12:28
Works for me. Website rendering on mobile devices is still less than brilliant, but it's usable at least and the titles behaviour mentioned by @jiffyclub above seems fixed for me.

**Comment by wking** [comment] 2013-02-28 12:32
Nobody wants it open after 2 days, so I'm closing this.  Feel free to open new issues with specific problems/suggestions for small-screen improvements as the spirit moves you ;).

**Closed as completed by wking** 2013-02-28 12:32 UTC
Labels: content enhancement, effort medium, website
